server:
  port: 8082

spring:
  application:
    name: CATALOG-SERVICE

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/revplay_catalog_db
    username: dharam
    password: dharam

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongForHS256Algorithm
  expiration: 86400000